steps:
  - id: "Rodando docker-compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose'
    args: [ '-f', 'docker-compose.yml', 'up', '-d' ]

  - id: "Docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: [ 'ps']